From registry.cn-hangzhou.aliyuncs.com/pjan/python:3.7-lightweight
MAINTAINER PJAN
WORKDIR /flask/flask_simple/
COPY . /flask/flask_simple/
RUN pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple flask
CMD ["python", "hello_world.py"]
